version: 2

registries:
  microsoft-npm-proxy:
    type: npm-registry
    url: https://packagefeedproxy.microsoft.io/npm/
    replaces-base: true

updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - microsoft-npm-proxy
    schedule:
      interval: "weekly"
